name: Keep Supabase Active
on:
  schedule:
    - cron: '0 0 */3 * *' # Runs every 3 days at midnight UTC
jobs:
  keepAlive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Keep-Alive
        run: curl -X GET "https://your-vercel-project.vercel.app/api/keep-alive"
