name: Keep Supabase Active
on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight UTC
jobs:
  keepAlive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Keep-Alive
        run: curl -X GET "https://lux-van-rental.vercel.app/api/keep-alive"
